# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_course_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buck',
            name='student',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
