# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20170729_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER'), ('OBSERVER', 'OBSERVER'), ('MERCHANT', 'MERCHANT')], default='TEACHER', max_length=20),
        ),
        migrations.AddField(
            model_name='missingassignment',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.UserProfile'),
        ),
        migrations.AddField(
            model_name='missingassignment',
            name='students',
            field=models.ManyToManyField(to='bank.Student'),
        ),
    ]
