# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20170805_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingassignment',
            name='entered_by',
        ),
        migrations.AddField(
            model_name='missingassignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingassignment',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
