# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20170805_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBehaviorGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Student')),
            ],
        ),
    ]
