# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20170808_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.TimeField(),
        ),
    ]
