# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20170808_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.CourseReport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Student')),
            ],
        ),
    ]
