# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_behaviornote'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
