# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_deposit_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['student__last_name', 'student__first_name']},
        ),
        migrations.AlterField(
            model_name='personalbehaviorgoal',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
