# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_deposit_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cac_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pass_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
