# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_auto_20170818_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='iss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursereport',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursereport',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
