# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_purchaseitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='iss',
            field=models.BooleanField(default=False),
        ),
    ]
