# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20170825_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='courses',
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.Schedule'),
            preserve_default=False,
        ),
    ]
