# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_absence_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereport',
            options={'ordering': ['course__hour', 'course__grade']},
        ),
    ]
