# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_auto_20170825_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='sample', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.Schedule'),
            preserve_default=False,
        ),
    ]
