# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_auto_20170828_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slots',
            field=models.ManyToManyField(to='bank.TimeSlot'),
        ),
    ]
