# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_auto_20170926_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['grade', 'name', 'section_number']},
        ),
    ]
