# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20170828_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
