# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20170926_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='missingassignment',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
