# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_course_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('courses', models.ManyToManyField(to='bank.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Student')),
            ],
        ),
    ]
