# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
