# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_absence_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['grade', 'name', 'section_number']},
        ),
        migrations.AlterModelOptions(
            name='coursereport',
            options={'ordering': ['course__hour', 'course__grade']},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='missingassignment',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
