# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('tier_two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='CheckAndConnectGoal',
            new_name='T2Goal',
        ),
        migrations.RenameModel(
            old_name='CheckAndConnectProfile',
            new_name='T2Profile',
        ),
        migrations.RemoveField(
            model_name='checkandconnectreport',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='checkandconnectreport',
            name='report',
        ),
        migrations.DeleteModel(
            name='CheckAndConnectReport',
        ),
        migrations.AddField(
            model_name='t2report',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tier_two.T2Goal'),
        ),
        migrations.AddField(
            model_name='t2report',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.CourseReport'),
        ),
    ]
