# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tier_two', '0002_auto_20170720_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T2Goal',
            new_name='TTwoGoal',
        ),
        migrations.RenameModel(
            old_name='T2Profile',
            new_name='TTwoProfile',
        ),
        migrations.RenameModel(
            old_name='T2Report',
            new_name='TTwoReport',
        ),
    ]
